/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sauravsharan

import kotlin.test.Test
import kotlin.test.assertTrue

class ChatGPTTest {
    @Test fun testSomeLibraryMethod() {
        val api = OpenAiService("").build();

    }
}
